version: '3.9'

services:

  database:
    image: postgres:14.3
    env_file:
      - .env_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/website
    ports:
      - 80:8000
    env_file:
      - .env_prod
    depends_on:
      - database

volumes:
  postgres_data: